-- MySQL Script generated by MySQL Workbench
-- mer. 29 janv. 2020 00:34:49 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escape_sorbonne
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escape_sorbonne
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escape_sorbonne` ;
USE `escape_sorbonne` ;

-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Articles` (
  `idArticles` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `Notes` INT NULL,
  PRIMARY KEY (`idArticles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Reponses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Reponses` (
  `idReponses` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `Articles_idArticles` INT NOT NULL,
  PRIMARY KEY (`idReponses`),
  INDEX `fk_Reponses_Articles1_idx` (`Articles_idArticles` ASC) VISIBLE,
  CONSTRAINT `fk_Reponses_Articles1`
    FOREIGN KEY (`Articles_idArticles`)
    REFERENCES `escape_sorbonne`.`Articles` (`idArticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Questions` (
  `idQuestions` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  `Reponses_idReponses` INT NOT NULL,
  PRIMARY KEY (`idQuestions`),
  INDEX `fk_Questions_Reponses_idx` (`Reponses_idReponses` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Reponses`
    FOREIGN KEY (`Reponses_idReponses`)
    REFERENCES `escape_sorbonne`.`Reponses` (`idReponses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Indices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Indices` (
  `Idindices` INT NOT NULL,
  `text` VARCHAR(45) NULL,
  PRIMARY KEY (`Idindices`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Resultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Resultats` (
  `idResultats` INT NOT NULL,
  PRIMARY KEY (`idResultats`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escape_sorbonne`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escape_sorbonne`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtilisateur`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
